# Use an official Python runtime as a parent image
FROM python:3.9

# Install Docker
RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary source files into the container
COPY src/ /app/src/

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the entire project directory into the container
COPY . .

# Specify the command to run when the container starts
CMD ["make", "unit-tests"]
